all:
	g++ -mconsole -Isrc/include -Lsrc/lib -o main main.cpp Scenes/settings_scene.cpp Scenes/mainmenu_scene.cpp Scenes/pause_scene.cpp Scenes/Level1Scene.cpp Assets/tank.cpp Utils/Utils.cpp Utils/MusicPlayer.cpp Utils/SoundPlayer.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_mixer -lbox2d -static-libgcc -static-libstdc++
